# Generated by Django 6.0.5 on 2026-06-17 22:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per unit (used for inventory valuation and test costing)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Revenue charged per test run', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
